version: "3.9"
services:

  pumpkinbeertaste:
    image: 246282979715.dkr.ecr.us-east-1.amazonaws.com/pumpkintasting:1.0.5
    container_name: pumpkin_beer_taste
    restart: always
    depends_on:
      - sqlserverdb
    environment:
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - LogTo__EndPoint=${LogTo__EndPoint}
      - LogTo__AppId=${LogTo__AppId}
      - LogTo__AppSecret=${LogTo__AppSecret}
      - LogTo__Scopes__0=${LogTo__Scopes__0}
      - LogTo__Scopes__1=${LogTo__Scopes__1}
      - LogTo__Scopes__2=${LogTo__Scopes__2}
    networks:
      - shared-traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pumpkintasting.rule=Host(`${PUMPKINTASTING_ROUTER_HOST}`) || Host(`${PUMPKINTASTING_ROUTER_HOST2}`)"
      - "traefik.http.routers.pumpkintasting.entrypoints=websecure"
      - "traefik.http.routers.pumpkintasting.service=pumpkintasting-service"
      - "traefik.http.services.pumpkintasting-service.loadbalancer.server.port=80"
      - "traefik.http.routers.pumpkintasting.tls.certresolver=${TRAEFIK_SERVICES_CERTRESOLVER}"
      - "traefik.http.routers.pumpkintasting.tls=true"

  sqlserverdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    restart: always
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=${SQLServerPassword}
      - TZ=America/Chicago
    networks:
      - shared-traefiknet
    volumes:
      - 'sqlvolume:/var/opt/mssq'

volumes:
    sqlvolume: {}

networks:
  shared-traefiknet:
    external: true
