version: "3.9" 
services:

  pumpkinbeertaste-app:
    build:
      context: .
      dockerfile: src/Pumpkin.Beer.Taste/Dockerfile
    container_name: pumpkinbeertaste-app
    ports:
      - "5080:8080"
    depends_on:
      - pumpkinbeertaste-db
    environment:
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - KeyCloak__Authority=${KeyCloak__Authority}
      - KeyCloak__ClientId=${KeyCloak__ClientId}
      - KeyCloak__ClientSecret=${KeyCloak__ClientSecret}

  pumpkinbeertaste-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: pumpkinbeertaste-db
    command: /bin/bash ./entrypoint.sh
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=${SQLServerSAPassword}
      - TZ=America/Chicago
      - SQLServerSAPassword=${SQLServerSAPassword}
      - SQLServerUserPassword=${SQLServerUserPassword}
    volumes:
      - 'pumpkinbeertaste-db:/var/opt/mssq'
      - ./CreateDatabase/entrypoint.sh:/entrypoint.sh
      - ./CreateDatabase/db-init.sh:/db-init.sh
      - ./CreateDatabase/db-init.sql:/db-init.sql

volumes:
    pumpkinbeertaste-db: {}
