name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish with dotnet
      run: dotnet publish --configuration Release --self-contained true -r linux-x64 -o ${{ github.github_workspace }}\publish
    - name: stop site
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        script_stop: true
        script: |
          sudo systemctl stop kestrel-blindtastetest.service
          sudo rm -rf /usr/share/nginx/html/*
    - name: copy file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        source: ${{ github.github_workspace }}\publish
        target: /home/ec2-user/drop
    - name: start site
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        script_stop: true
        script: |
          sudo cp -r /home/ec2-user/drop/publish/* /usr/share/nginx/html
          sudo chgrp nginx /usr/share/nginx/html/Pumpkin.Beer.Taste
          sudo chmod g+x /usr/share/nginx/html/Pumpkin.Beer.Taste
          sudo systemctl start kestrel-blindtastetest.service
          sudo rm -rf /home/ec2-user/drop